apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumen-persistente
  labels:
    api: reticula-api-des
    type: local
spec:
  storageClassName: db
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/api-ret/db/"